#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get -y update
apt-get -y install nginx
service nginx start
echo "Hello World!" > /var/www/html/index.html
echo  "Ceci n'est pas une page" > /var/www/html/404.html
new_string="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://bolexzy.hashnode.dev/;\n\t}\
\n\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\tinternal;\n\t}"
sed -i "s|server_name _;|${new_string}|" /etc/nginx/sites-available/default
service nginx restart
