#!/usr/bin/env bash
# Configures nginx to run as nginx user
## nginx must be listening on all active IPs on port 8080
### cannot use apt-get remove


# Change Nginx user
sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf

# Change Nginx listen directive
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# give owner permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf

# kill procceses that may interrupt
pkill apache2

# Start Nginx
sudo -u nginx service nginx restart
